version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: selenium/standalone-chrome:3.11.0
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: example
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
            pip install packaging
            pip install webdriver-manager
            pip install selenium
      - run:
          name: run tests
          command: python pur_beurre/manage.py test pur_beurre/.
          environment:
            TESTING: True


workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint